stages:
  - doc
  - build
  - test

pages:
  stage: doc
  tags:
    - docker
    - linux
  image: rust:latest

  script:
    - mkdir -p public
    - rustup target add thumbv7m-none-eabi
    - cd {{project-name}}
    - cargo doc --no-deps
    - cp ./target/thumbv7m-none-eabi/doc/* ../public -r
    - echo "<meta http-equiv=refresh content=0;url={{project-name}}/index.html>" > ../public/index.html
    - cd ../public/
    - ls -la
  artifacts:
    paths:
      - public

  only:
    - main


build-release:
  tags:
    - docker
    - linux
  stage: build
  image: rust:latest
  script:
    - echo "Building"
    - rustup target add thumbv7m-none-eabi
    - cargo install cargo-binutils
    - rustup component add llvm-tools-preview
    - cd ./{{project-name}}
    - cargo size --release -- -A
  artifacts:
    paths:
      - ./{{project-name}}/target/thumbv7m-none-eabi/release/{{project-name}}

test:
  tags:
    - docker
    - linux
  stage: test
  image: rust:latest
  script:
    - echo "Building"
    - cd ./lib/{{sublibrary}}
    - cargo test
