stages:
  - doc
  - build
  - test

pages:
  stage: doc
  tags:
    - docker
    - linux
  image: rust:latest

  script:
    - cd {{project-name}}
    - cargo doc --target-dir ../public

  artifacts:
    paths:
      - public

  only:
    - master


build-release:
  tags:
    - docker
    - linux
  stage: build
  image: rust:latest
  script:
    - echo "Building"
    - rustup target add thumbv7m-none-eabi
    - cargo install cargo-binutils
    - rustup component add llvm-tools-preview
    - cd ./{{project-name}}
    - cargo size --release -- -A
  artifacts:
    paths:
      - ./target/thumbv7m-none-eabi/release/{{project-name}}

test:
  tags:
    - docker
    - linux
  stage: test
  image: rust:latest
  script:
    - echo "Building"
    - cd ./lib/{{sublibrary}}
    - cargo test
